name: Update the branch for upstream pull request

on:
  workflow_dispatch:

concurrency:
  group: export

permissions:
  contents: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git remote add upstream https://github.com/bluesky-social/social-app.git
          git fetch upstream main
          git checkout -b export upstream/main
          git restore --source origin/l10n_id src/**/id/*
          git add --all
          if ! git diff-index --quiet HEAD; then
            git config user.name Indonesian
            git config user.email github-actions@github.com
            git commit -m 'Update Indonesian translation'
            git push -f origin HEAD
          fi
